export type TabsRoutes =
  | "Home"
  | "Chapters"
  | "Menu"
  | "Calendar"
  | "Random"
  | "Music"
  | "Settings"
  | "Favorites"
  | "Developer"
  | "Room"
  | "Search";

export type RankingTypes =
  | "Newcomer"
  | "Seeker"
  | "Listener"
  | "Learner"
  | "Reader"
  | "Follower"
  | "Disciple"
  | "Messenger"
  | "Scribe"
  | "Believer"
  | "Preacher"
  | "Elder"
  | "Shepherd"
  | "Guardian"
  | "Wisdom Bearer"
  | "Master of the Word"
  | "Light Bringer"
  | "Covenant Keeper"
  | "Divine Scholar"
  | "Heaven’s Herald";
